"""empty message

Revision ID: 99aab350c212
Revises: 22643c4fc2cf
Create Date: 2019-08-27 18:55:14.192112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99aab350c212'
down_revision = '22643c4fc2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articletype', sa.Column('othername', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articletype', 'othername')
    # ### end Alembic commands ###
