"""empty message

Revision ID: 9ab3fa8d9712
Revises: cce8f0a9058d
Create Date: 2019-08-28 20:08:50.654385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab3fa8d9712'
down_revision = 'cce8f0a9058d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'title')
    # ### end Alembic commands ###
