"""empty message

Revision ID: 9f35bbcd58b9
Revises: bc2e0aa2c2ba
Create Date: 2019-08-28 22:10:50.587735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f35bbcd58b9'
down_revision = 'bc2e0aa2c2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('tag', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'tag')
    # ### end Alembic commands ###
