"""empty message

Revision ID: bc2e0aa2c2ba
Revises: 9ab3fa8d9712
Create Date: 2019-08-28 20:22:30.198951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2e0aa2c2ba'
down_revision = '9ab3fa8d9712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('introduction', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'introduction')
    # ### end Alembic commands ###
