"""empty message

Revision ID: cce8f0a9058d
Revises: 99aab350c212
Create Date: 2019-08-27 19:40:47.973489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce8f0a9058d'
down_revision = '99aab350c212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('introduce', sa.String(length=255), nullable=True))
    op.add_column('article', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'num')
    op.drop_column('article', 'introduce')
    # ### end Alembic commands ###
